// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TradeNet11.Data;

#nullable disable

namespace TradeNet11.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260424093000_AddRuleViolationColumn")]
    partial class AddRuleViolationColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TradeNet11.Models.Audit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedOfficerId")
                        .HasColumnType("int");

                    b.Property<string>("AuditTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChecklistJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ComplianceCaseId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Findings")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedOfficerId");

                    b.HasIndex("ComplianceCaseId");

                    b.ToTable("Audits");
                });

            modelBuilder.Entity("TradeNet11.Models.ComplianceCase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedOfficerId")
                        .HasColumnType("int");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IssueType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedOfficerId");

                    b.ToTable("ComplianceCases");
                });

            modelBuilder.Entity("TradeNet11.Models.ComplianceNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AssignedOfficerId")
                        .HasColumnType("int");

                    b.Property<int?>("AuditId")
                        .HasColumnType("int");

                    b.Property<int?>("ComplianceCaseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedOfficerId");

                    b.HasIndex("AuditId");

                    b.HasIndex("ComplianceCaseId");

                    b.ToTable("ComplianceNotifications");
                });

            modelBuilder.Entity("TradeNet11.Models.ComplianceOfficer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ComplianceOfficers");
                });

            modelBuilder.Entity("TradeNet11.Models.ComplianceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionTaken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ComplianceCaseId")
                        .HasColumnType("int");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OfficerId")
                        .HasColumnType("int");

                    b.Property<string>("OfficerRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RuleViolation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ComplianceCaseId");

                    b.HasIndex("OfficerId");

                    b.ToTable("ComplianceRecords");
                });

            modelBuilder.Entity("TradeNet11.Models.ProgramCompliance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EligibilityStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FundUsageSummary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsMisuseFlag")
                        .HasColumnType("bit");

                    b.Property<string>("ProgramName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReviewedByOfficerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReviewedByOfficerId");

                    b.ToTable("ProgramCompliances");
                });

            modelBuilder.Entity("TradeNet11.Models.Audit", b =>
                {
                    b.HasOne("TradeNet11.Models.ComplianceOfficer", "AssignedOfficer")
                        .WithMany()
                        .HasForeignKey("AssignedOfficerId");

                    b.HasOne("TradeNet11.Models.ComplianceCase", "ComplianceCase")
                        .WithMany()
                        .HasForeignKey("ComplianceCaseId");

                    b.Navigation("AssignedOfficer");

                    b.Navigation("ComplianceCase");
                });

            modelBuilder.Entity("TradeNet11.Models.ComplianceCase", b =>
                {
                    b.HasOne("TradeNet11.Models.ComplianceOfficer", "AssignedOfficer")
                        .WithMany()
                        .HasForeignKey("AssignedOfficerId");

                    b.Navigation("AssignedOfficer");
                });

            modelBuilder.Entity("TradeNet11.Models.ComplianceNotification", b =>
                {
                    b.HasOne("TradeNet11.Models.ComplianceOfficer", "AssignedOfficer")
                        .WithMany()
                        .HasForeignKey("AssignedOfficerId");

                    b.HasOne("TradeNet11.Models.Audit", "Audit")
                        .WithMany()
                        .HasForeignKey("AuditId");

                    b.HasOne("TradeNet11.Models.ComplianceCase", "ComplianceCase")
                        .WithMany()
                        .HasForeignKey("ComplianceCaseId");

                    b.Navigation("AssignedOfficer");

                    b.Navigation("Audit");

                    b.Navigation("ComplianceCase");
                });

            modelBuilder.Entity("TradeNet11.Models.ComplianceRecord", b =>
                {
                    b.HasOne("TradeNet11.Models.ComplianceCase", "ComplianceCase")
                        .WithMany("Records")
                        .HasForeignKey("ComplianceCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TradeNet11.Models.ComplianceOfficer", "Officer")
                        .WithMany()
                        .HasForeignKey("OfficerId");

                    b.Navigation("ComplianceCase");

                    b.Navigation("Officer");
                });

            modelBuilder.Entity("TradeNet11.Models.ProgramCompliance", b =>
                {
                    b.HasOne("TradeNet11.Models.ComplianceOfficer", "ReviewedByOfficer")
                        .WithMany()
                        .HasForeignKey("ReviewedByOfficerId");

                    b.Navigation("ReviewedByOfficer");
                });

            modelBuilder.Entity("TradeNet11.Models.ComplianceCase", b =>
                {
                    b.Navigation("Records");
                });
#pragma warning restore 612, 618
        }
    }
}
